name: Update Index

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update:
    name: Update File Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Run python script
        run: |
          cd .github
          python -m pip install requests asyncio
          python Update_index.py
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: 每日更新文件索引'
          add: |
            'path.json'
            'files.json'
            'othername.json'
